"""empty message

Revision ID: 44714a36fe29
Revises: 939c2f04d772
Create Date: 2025-05-07 17:02:10.543029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44714a36fe29'
down_revision = '939c2f04d772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comments_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
