"""empty message

Revision ID: 7e448ef4b121
Revises: 3caf5ff91113
Create Date: 2025-05-07 16:04:16.156678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e448ef4b121'
down_revision = '3caf5ff91113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('types', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medias')
    # ### end Alembic commands ###
