"""empty message

Revision ID: 939c2f04d772
Revises: 7e448ef4b121
Create Date: 2025-05-07 16:38:41.537703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939c2f04d772'
down_revision = '7e448ef4b121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_to_id', 'user_from_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
